CREATE DATABASE IF NOT EXISTS SDProductos;
CREATE DATABASE IF NOT EXISTS SDClientes;
CREATE DATABASE IF NOT EXISTS SDProveedores;
CREATE DATABASE IF NOT EXISTS SDUsuarios;
CREATE DATABASE IF NOT EXISTS SDVentas;
