spring.application.name=msventas
server.port=8086

# ===============================
# CONFIGURACION DE LA BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/SDVentas?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Bogota
# ¡OJO AQUÍ! Asegúrate de que esta sea la contraseña real de tu Ubuntu
spring.datasource.username=root
spring.datasource.password=toor 

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LA LÍNEA MÁGICA PARA SOLUCIONAR EL ERROR DEL DIALECTO:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# COMUNICACIÓN CON OTROS MICROSERVICIOS
# ===============================
service.clientes.url=http://${CLIENTES_HOST:localhost}:8080/msclientes
service.productos.url=http://${PRODUCTOS_HOST:localhost}:8080/msproductos